[project]
name = "lfmc"
version = "0.1.0"

[project.scripts]
create-csv = "lfmc.prepare.create_csv:main"

[tool.setuptools]
packages = ["lfmc"]

[tool.ruff]
lint.extend-select = ["I", "TID252"]
line-length = 99
