name: CI
on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions/setup-python@v4
      with:
        python-version: 3.12
        cache: 'pip'
    - name: 'install dependencies'
      run: pip install -r requirements-dev.txt
    - name: 'check formatting'
      run: python -m ruff format --check
      working-directory: lfmc
    - name: 'lint'
      run: python -m ruff check
      working-directory: lfmc
    - name: 'type check'
      run: python -m mypy .
      working-directory: lfmc
